# Generated by Django 3.2.16 on 2023-06-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('income_group', models.IntegerField()),
                ('sensing', models.FloatField()),
                ('introvert', models.FloatField()),
                ('Judging', models.FloatField()),
                ('Thinking', models.FloatField()),
                ('logical_intelligence', models.FloatField()),
                ('Nature_intelligence', models.FloatField()),
                ('Visual_intelligence', models.FloatField()),
                ('Musical_intelligence', models.FloatField()),
                ('Body_intelligence', models.FloatField()),
                ('Interpersonal_intelligence', models.FloatField()),
                ('Intrapersonal_intelligence', models.FloatField()),
                ('Verbal_intelligence', models.FloatField()),
                ('Existential_intelligence', models.FloatField()),
                ('Engineering_Field1', models.CharField(max_length=200)),
                ('Engineering_Field2', models.CharField(max_length=200)),
                ('Engineering_Field3', models.CharField(max_length=200)),
                ('Engineering_Field4', models.CharField(max_length=200)),
                ('Engineering_Field5', models.CharField(max_length=200)),
                ('Medical_Field1', models.CharField(max_length=200)),
                ('Medical_Field2', models.CharField(max_length=200)),
                ('Medical_Field3', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True, max_length=500)),
                ('country', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
